import pool from './database.js';
import bcrypt from 'bcryptjs';
import { v4 as uuidv4 } from 'uuid';

async function seed() {
  try {
    console.log('🌱 Seeding database...');

    // Clear existing data (development only)
    // Order matters because of foreign key constraints
    await pool.query('DELETE FROM bookings');
    await pool.query('DELETE FROM reviews');
    await pool.query('DELETE FROM vehicles');
    await pool.query('DELETE FROM locations');

    // Create or get test user
    const testEmail = 'test@example.com';
    const passwordHash = await bcrypt.hash('password123', 10);

    const userResult = await pool.query(
      `INSERT INTO users (id, email, password_hash, email_verified)
       VALUES ($1, $2, $3, $4)
       ON CONFLICT (email) DO UPDATE
       SET email = EXCLUDED.email
       RETURNING id`,
      [uuidv4(), testEmail, passwordHash, true]
    );

    const userId: string = userResult.rows[0].id;

    await pool.query(
      'INSERT INTO profiles (id, full_name, last_name, email, phone_number) VALUES ($1, $2, $3, $4, $5) ON CONFLICT (id) DO NOTHING',
      [userId, 'Test', 'User', testEmail, '+1234567890']
    );

    // Create sample locations
    const locations = [
      {
        id: uuidv4(),
        name: 'Mannheim Central',
        country: 'Germany',
        city: 'Mannheim',
        postal_code: '68161',
        address: 'Bahnhofplatz 1',
        locations: ['Mannheim (49.489,8.467)'],
      },
      {
        id: uuidv4(),
        name: 'Frankfurt Airport',
        country: 'Germany',
        city: 'Frankfurt',
        postal_code: '60547',
        address: 'Flughafen Frankfurt',
        locations: ['Frankfurt (50.110,8.682)'],
      },
      {
        id: uuidv4(),
        name: 'Bremen Station',
        country: 'Germany',
        city: 'Bremen',
        postal_code: '28195',
        address: 'Hauptbahnhof',
        locations: ['Bremen (53.0793,8.8017)'],
      },
    ];

    for (const loc of locations) {
      await pool.query(
        `INSERT INTO locations (id, name, country, city, postal_code, address, locations)
         VALUES ($1, $2, $3, $4, $5, $6, $7) ON CONFLICT DO NOTHING`,
        [loc.id, loc.name, loc.country, loc.city, loc.postal_code, loc.address, loc.locations]
      );
    }

    // Create sample vehicles
    const vehicles = [
      {
        vehicleid: 'V001',
        brand: 'Audi',
        model: 'A6 Avant e-tron',
        year: 2024,
        vehicletype: 'Wagon',
        colors: 'Grey',
        locations: ['Berlin (52.5200,13.4050)'],
        priceperday: 210,
        availability: true,
        electricvehicle: true,
        carimg: '/cars/Audi A6 Avant e-tron.png',
        seats: 5,
        luggage: 4,
        horstpower: '350',
        ps: 350,
        consumption: '0L/100km',
        fuel: 'Electric',
        geartype: 'Automatic',
        featured: true,
        rating: 4.9,
      },
      {
        vehicleid: 'V002',
        brand: 'Audi',
        model: 'Q2',
        year: 2024,
        vehicletype: 'Crossover',
        colors: 'Grey Metallic',
        locations: ['Düsseldorf (51.2277,6.7735)'],
        priceperday: 120,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Audi Q2.png',
        seats: 5,
        luggage: 2,
        horstpower: '150',
        ps: 150,
        consumption: '6.0L/100km',
        fuel: 'Gasoline',
        geartype: 'Manual',
        featured: false,
        rating: 4.4,
      },
      
      {
        vehicleid: 'V006',
        brand: 'BMW',
        model: '5 Series',
        year: 2018,
        vehicletype: 'Sedan',
        colors: 'Black',
        locations: ['Frankfurt (50.1100,8.6820)'],
        priceperday: 135,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/BMW 3 Series.jpg',
        seats: 5,
        luggage: 3,
        horstpower: '252',
        ps: 252,
        consumption: '7.0L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.4,
      },
      {
        vehicleid: 'V007',
        brand: 'BMW',
        model: 'M135i',
        year: 2019,
        vehicletype: 'Hatchback',
        colors: 'Grey Metallic',
        locations: ['Dortmund (51.5136,7.4653)'],
        priceperday: 160,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/BMW M135i.png',
        seats: 5,
        luggage: 2,
        horstpower: '306',
        ps: 306,
        consumption: '7.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: true,
        rating: 4.7,
      },
      {
        vehicleid: 'V009',
        brand: 'BMW',
        model: 'M340 Touring',
        year: 2018,
        vehicletype: 'Wagon',
        colors: 'Black',
        locations: ['Essen (51.4556,7.0116)'],
        priceperday: 145,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/BMW M340 Touring.png',
        seats: 5,
        luggage: 4,
        horstpower: '248',
        ps: 248,
        consumption: '8.9L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: true,
        rating: 4.6,
      },
      {
        vehicleid: 'V010',
        brand: 'BMW',
        model: 'M850 Coupe',
        year: 2024,
        vehicletype: 'Coupe',
        colors: 'Silver Metallic',
        locations: ['Wuppertal (51.2562,7.1508)'],
        priceperday: 320,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/BMW M850 Coupe.png',
        seats: 4,
        luggage: 2,
        horstpower: '523',
        ps: 523,
        consumption: '12.3L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: true,
        rating: 4.9,
      },
      {
        vehicleid: 'V014',
        brand: 'BMW',
        model: 'X5',
        year: 2021,
        vehicletype: 'SUV',
        colors: 'Black',
        locations: ['München (48.1351,11.5820)'],
        priceperday: 200,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/BMW X3 M50.png',
        seats: 5,
        luggage: 3,
        horstpower: '335',
        ps: 335,
        consumption: '9.2L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: true,
        rating: 4.7,
      },
      {
        vehicleid: 'V015',
        brand: 'Cadillac',
        model: 'XTS',
        year: 2022,
        vehicletype: 'Sedan',
        colors: 'Black',
        locations: ['Frankfurt (50.1100,8.6820)'],
        priceperday: 180,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Cadillac XTS.jpg',
        seats: 5,
        luggage: 2,
        horstpower: '304',
        ps: 304,
        consumption: '10.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: true,
        rating: 4.5,
      },
      {
        vehicleid: 'V016',
        brand: 'Chevrolet',
        model: 'Equinox',
        year: 2022,
        vehicletype: 'SUV',
        colors: 'Black',
        locations: ['Köln (50.9375,6.9603)'],
        priceperday: 125,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Chevrolet Equinox.jpg',
        seats: 5,
        luggage: 3,
        horstpower: '170',
        ps: 170,
        consumption: '8.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.2,
      },
      {
        vehicleid: 'V017',
        brand: 'Chevrolet',
        model: 'Malibu',
        year: 2019,
        vehicletype: 'Sedan',
        colors: 'Silver',
        locations: ['Hamburg (53.5511,9.9937)'],
        priceperday: 105,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Chevrolet Aveo.png',
        seats: 5,
        luggage: 2,
        horstpower: '160',
        ps: 160,
        consumption: '7.2L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.1,
      },
      {
        vehicleid: 'V018',
        brand: 'Chevrolet',
        model: 'Traverse',
        year: 2024,
        vehicletype: 'SUV',
        colors: 'Black',
        locations: ['Düsseldorf (51.2277,6.7735)'],
        priceperday: 140,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Chevrolet Traverse.png',
        seats: 7,
        luggage: 4,
        horstpower: '328',
        ps: 328,
        consumption: '9.8L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.4,
      },
      {
        vehicleid: 'V019',
        brand: 'Chrysler',
        model: '300',
        year: 2021,
        vehicletype: 'Sedan',
        colors: 'Black',
        locations: ['Stuttgart (48.7758,9.1829)'],
        priceperday: 130,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Chrysler S300.jpg',
        seats: 5,
        luggage: 2,
        horstpower: '292',
        ps: 292,
        consumption: '9.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.3,
      },
      {
        vehicleid: 'V020',
        brand: 'Citroen',
        model: 'e-C3',
        year: 2022,
        vehicletype: 'Hatchback',
        colors: 'White',
        locations: ['Dortmund (51.5136,7.4653)'],
        priceperday: 95,
        availability: true,
        electricvehicle: true,
        carimg: '/cars/Citroen C3.jpg',
        seats: 5,
        luggage: 2,
        horstpower: '56',
        ps: 56,
        consumption: '0L/100km',
        fuel: 'Electric',
        geartype: 'Automatic',
        featured: false,
        rating: 4.2,
      },
      {
        vehicleid: 'V021',
        brand: 'Dodge',
        model: 'Challenger',
        year: 2021,
        vehicletype: 'Coupe',
        colors: 'Red',
        locations: ['Berlin (52.5200,13.4050)'],
        priceperday: 195,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Dodge Challenger.jpg',
        seats: 4,
        luggage: 1,
        horstpower: '303',
        ps: 303,
        consumption: '11.2L/100km',
        fuel: 'Gasoline',
        geartype: 'Manual',
        featured: true,
        rating: 4.6,
      },
      {
        vehicleid: 'V023',
        brand: 'Dodge',
        model: 'Grand Caravan',
        year: 2021,
        vehicletype: 'SUV',
        colors: 'Blue',
        locations: ['Wuppertal (51.2562,7.1508)'],
        priceperday: 135,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Dodge Grand Caravan.jpg',
        seats: 7,
        luggage: 4,
        horstpower: '287',
        ps: 287,
        consumption: '10.4L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.2,
      },
      {
        vehicleid: 'V024',
        brand: 'Ford',
        model: 'Edge',
        year: 2021,
        vehicletype: 'SUV',
        colors: 'Red',
        locations: ['Dresden (51.0504,13.7373)'],
        priceperday: 150,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Ford Edge.jpg',
        seats: 5,
        luggage: 3,
        horstpower: '250',
        ps: 250,
        consumption: '9.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.4,
      },
      {
        vehicleid: 'V025',
        brand: 'Ford',
        model: 'Escape',
        year: 2022,
        vehicletype: 'SUV',
        colors: 'Blue',
        locations: ['Hannover (52.3759,9.7320)'],
        priceperday: 125,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Ford Escape_2022.jpg',
        seats: 5,
        luggage: 3,
        horstpower: '181',
        ps: 181,
        consumption: '8.2L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.3,
      },
      {
        vehicleid: 'V026',
        brand: 'Ford',
        model: 'Explorer',
        year: 2021,
        vehicletype: 'SUV',
        colors: 'Blue',
        locations: ['Berlin (52.5200,13.4050)'],
        priceperday: 165,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Ford Explorer.jpg',
        seats: 7,
        luggage: 4,
        horstpower: '300',
        ps: 300,
        consumption: '10.2L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: true,
        rating: 4.5,
      },
      {
        vehicleid: 'V027',
        brand: 'Ford',
        model: 'Mustang',
        year: 2020,
        vehicletype: 'Coupe',
        colors: 'Blue',
        locations: ['München (48.1351,11.5820)'],
        priceperday: 185,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Ford Mustang.png',
        seats: 4,
        luggage: 1,
        horstpower: '310',
        ps: 310,
        consumption: '11.8L/100km',
        fuel: 'Gasoline',
        geartype: 'Manual',
        featured: true,
        rating: 4.6,
      },
      {
        vehicleid: 'V029',
        brand: 'Ford',
        model: 'Transit Wagon',
        year: 2021,
        vehicletype: 'VAN',
        colors: 'White',
        locations: ['Köln (50.9375,6.9603)'],
        priceperday: 140,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Ford Transit.png',
        seats: 15,
        luggage: 5,
        horstpower: '275',
        ps: 275,
        consumption: '12.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.1,
      },
      {
        vehicleid: 'V030',
        brand: 'GMC',
        model: 'Yukon XL',
        year: 2021,
        vehicletype: 'SUV',
        colors: 'Black',
        locations: ['Hamburg (53.5511,9.9937)'],
        priceperday: 220,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/GMC Yukon XL.png',
        seats: 8,
        luggage: 4,
        horstpower: '355',
        ps: 355,
        consumption: '13.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: true,
        rating: 4.6,
      },
      {
        vehicleid: 'V031',
        brand: 'Hyundai',
        model: 'Elantra',
        year: 2019,
        vehicletype: 'Sedan',
        colors: 'Silver',
        locations: ['Düsseldorf (51.2277,6.7735)'],
        priceperday: 100,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Hyundai Elantra.png',
        seats: 5,
        luggage: 2,
        horstpower: '147',
        ps: 147,
        consumption: '7.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Manual',
        featured: false,
        rating: 4.2,
      },
      {
        vehicleid: 'V032',
        brand: 'Hyundai',
        model: 'Tucson',
        year: 2023,
        vehicletype: 'SUV',
        colors: 'Black',
        locations: ['Stuttgart (48.7758,9.1829)'],
        priceperday: 130,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Hyundai Tucson.png',
        seats: 5,
        luggage: 3,
        horstpower: '187',
        ps: 187,
        consumption: '8.0L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.4,
      },
      {
        vehicleid: 'V033',
        brand: 'Jeep',
        model: 'Patriot',
        year: 2023,
        vehicletype: 'SUV',
        colors: 'Silver Metallic',
        locations: ['Dortmund (51.5136,7.4653)'],
        priceperday: 115,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Jeep Patriot.jpg',
        seats: 5,
        luggage: 2,
        horstpower: '200',
        ps: 200,
        consumption: '8.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Manual',
        featured: false,
        rating: 4.1,
      },
      {
        vehicleid: 'V034',
        brand: 'Kia',
        model: 'Soul',
        year: 2021,
        vehicletype: 'Hatchback',
        colors: 'Turquoise',
        locations: ['Essen (51.4556,7.0116)'],
        priceperday: 95,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Kia Soul.png',
        seats: 5,
        luggage: 2,
        horstpower: '147',
        ps: 147,
        consumption: '7.0L/100km',
        fuel: 'Gasoline',
        geartype: 'Manual',
        featured: false,
        rating: 4.0,
      },
      {
        vehicleid: 'V035',
        brand: 'Lexus',
        model: 'ES 300h',
        year: 2023,
        vehicletype: 'Sedan',
        colors: 'White',
        locations: ['Wuppertal (51.2562,7.1508)'],
        priceperday: 175,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Lexus ES 300h.jpg',
        seats: 5,
        luggage: 2,
        horstpower: '215',
        ps: 215,
        consumption: '5.3L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: true,
        rating: 4.7,
      },
      {
        vehicleid: 'V036',
        brand: 'Mercedes-Benz',
        model: 'C-Class',
        year: 2020,
        vehicletype: 'Sedan',
        colors: 'Silver Metallic',
        locations: ['Dresden (51.0504,13.7373)'],
        priceperday: 195,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Mercedes C-Classe Silver.jpg',
        seats: 5,
        luggage: 2,
        horstpower: '255',
        ps: 255,
        consumption: '8.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: true,
        rating: 4.8,
      },
    
      {
        vehicleid: 'V038',
        brand: 'Mercedes-Benz',
        model: 'Vito Tourer',
        year: 2020,
        vehicletype: 'VAN',
        colors: 'Green Metallic',
        locations: ['Berlin (52.5200,13.4050)'],
        priceperday: 155,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Mercedes-Benz Vito Tourer.jpg',
        seats: 9,
        luggage: 4,
        horstpower: '187',
        ps: 187,
        consumption: '6.8L/100km',
        fuel: 'Diesel',
        geartype: 'Automatic',
        featured: false,
        rating: 4.3,
      },
      {
        vehicleid: 'V039',
        brand: 'Mitsubishi',
        model: 'Mirage',
        year: 2021,
        vehicletype: 'Hatchback',
        colors: 'Red',
        locations: ['München (48.1351,11.5820)'],
        priceperday: 75,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Mitsubishi Mirage.png',
        seats: 5,
        luggage: 1,
        horstpower: '78',
        ps: 78,
        consumption: '5.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Manual',
        featured: false,
        rating: 3.8,
      },
      {
        vehicleid: 'V040',
        brand: 'Nissan',
        model: 'Leaf',
        year: 2020,
        vehicletype: 'Hatchback',
        colors: 'Silver Metallic',
        locations: ['Frankfurt (50.1100,8.6820)'],
        priceperday: 110,
        availability: true,
        electricvehicle: true,
        carimg: '/cars/Nissan Leaf.png',
        seats: 5,
        luggage: 2,
        horstpower: '147',
        ps: 147,
        consumption: '0L/100km',
        fuel: 'Electric',
        geartype: 'Automatic',
        featured: false,
        rating: 4.3,
      },
      {
        vehicleid: 'V041',
        brand: 'Nissan',
        model: 'Rogue',
        year: 2022,
        vehicletype: 'SUV',
        colors: 'Green Metallic',
        locations: ['Köln (50.9375,6.9603)'],
        priceperday: 135,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Nissan Rogue.jpg',
        seats: 5,
        luggage: 3,
        horstpower: '201',
        ps: 201,
        consumption: '7.8L/100km',
        fuel: 'Gasoline',
        geartype: 'Manual',
        featured: false,
        rating: 4.4,
      },
      {
        vehicleid: 'V042',
        brand: 'Porsche',
        model: '911 Carrera',
        year: 2024,
        vehicletype: 'Coupe',
        colors: 'Silver',
        locations: ['Hamburg (53.5511,9.9937)'],
        priceperday: 450,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Porsche 911 Carerra Turbo.png',
        seats: 4,
        luggage: 1,
        horstpower: '379',
        ps: 379,
        consumption: '11.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: true,
        rating: 4.9,
      },
      {
        vehicleid: 'V043',
        brand: 'Porsche',
        model: 'Cayenne',
        year: 2022,
        vehicletype: 'SUV',
        colors: 'Black',
        locations: ['Düsseldorf (51.2277,6.7735)'],
        priceperday: 280,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Porsche Cayenne.png',
        seats: 5,
        luggage: 3,
        horstpower: '335',
        ps: 335,
        consumption: '10.8L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: true,
        rating: 4.8,
      },
      {
        vehicleid: 'V044',
        brand: 'Porsche',
        model: 'Macan 4 Electric',
        year: 2023,
        vehicletype: 'SUV',
        colors: 'Blue',
        locations: ['Stuttgart (48.7758,9.1829)'],
        priceperday: 320,
        availability: true,
        electricvehicle: true,
        carimg: '/cars/Porsche Macan 4 Electric.jpg',
        seats: 5,
        luggage: 3,
        horstpower: '408',
        ps: 408,
        consumption: '0L/100km',
        fuel: 'Electric',
        geartype: 'Automatic',
        featured: true,
        rating: 4.9,
      },
      {
        vehicleid: 'V045',
        brand: 'Skoda',
        model: 'Octavia Estate',
        year: 2023,
        vehicletype: 'Wagon',
        colors: 'Dark Green',
        locations: ['Dortmund (51.5136,7.4653)'],
        priceperday: 110,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Skoda Octavia Estate.png',
        seats: 5,
        luggage: 4,
        horstpower: '150',
        ps: 150,
        consumption: '5.7L/100km',
        fuel: 'Gasoline',
        geartype: 'Manual',
        featured: false,
        rating: 4.3,
      },
      {
        vehicleid: 'V046',
        brand: 'Toyota',
        model: 'Prius',
        year: 2021,
        vehicletype: 'Hatchback',
        colors: 'Black',
        locations: ['Essen (51.4556,7.0116)'],
        priceperday: 105,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Toyota Prius Hybrid.png',
        seats: 5,
        luggage: 2,
        horstpower: '121',
        ps: 121,
        consumption: '4.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.5,
      },
      {
        vehicleid: 'V047',
        brand: 'Toyota',
        model: 'RAV4',
        year: 2022,
        vehicletype: 'SUV',
        colors: 'Black Metallic',
        locations: ['Wuppertal (51.2562,7.1508)'],
        priceperday: 140,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Toyota RAV4.png',
        seats: 5,
        luggage: 3,
        horstpower: '203',
        ps: 203,
        consumption: '7.8L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.5,
      },
      {
        vehicleid: 'V048',
        brand: 'Volkswagen',
        model: 'Caddy Maxi',
        year: 2024,
        vehicletype: 'SUV',
        colors: 'White',
        locations: ['Dresden (51.0504,13.7373)'],
        priceperday: 120,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Volkswagen Caddy Maxi.png',
        seats: 7,
        luggage: 4,
        horstpower: '115',
        ps: 115,
        consumption: '5.5L/100km',
        fuel: 'Diesel',
        geartype: 'Automatic',
        featured: false,
        rating: 4.2,
      },
      {
        vehicleid: 'V049',
        brand: 'Volkswagen',
        model: 'Golf Variant',
        year: 2023,
        vehicletype: 'Wagon',
        colors: 'Ocean Blue',
        locations: ['Hannover (52.3759,9.7320)'],
        priceperday: 115,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Volkswagen Golf Variant.png',
        seats: 5,
        luggage: 4,
        horstpower: '150',
        ps: 150,
        consumption: '5.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.4,
      },
      {
        vehicleid: 'V050',
        brand: 'Volkswagen',
        model: 'Golf',
        year: 2024,
        vehicletype: 'Hatchback',
        colors: 'Black',
        locations: ['Berlin (52.5200,13.4050)'],
        priceperday: 110,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Volkswagen Golf.png',
        seats: 5,
        luggage: 2,
        horstpower: '150',
        ps: 150,
        consumption: '5.8L/100km',
        fuel: 'Gasoline',
        geartype: 'Manual',
        featured: false,
        rating: 4.4,
      },
      {
        vehicleid: 'V051',
        brand: 'Volkswagen',
        model: 'Passat',
        year: 2020,
        vehicletype: 'Sedan',
        colors: 'Black',
        locations: ['München (48.1351,11.5820)'],
        priceperday: 125,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Volkswagen Passat.png',
        seats: 5,
        luggage: 2,
        horstpower: '174',
        ps: 174,
        consumption: '7.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Manual',
        featured: false,
        rating: 4.3,
      },
      {
        vehicleid: 'V052',
        brand: 'Volkswagen',
        model: 'T-Roc',
        year: 2022,
        vehicletype: 'Crossover',
        colors: 'Blue',
        locations: ['Frankfurt (50.1100,8.6820)'],
        priceperday: 130,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Volkswagen T-Roc.jpg',
        seats: 5,
        luggage: 2,
        horstpower: '150',
        ps: 150,
        consumption: '6.2L/100km',
        fuel: 'Gasoline',
        geartype: 'Manual',
        featured: false,
        rating: 4.3,
      },
      {
        vehicleid: 'V054',
        brand: 'Audi',
        model: 'A3',
        year: 2023,
        vehicletype: 'Hatchback',
        colors: 'Blue',
        locations: ['Berlin (52.5200,13.4050)'],
        priceperday: 125,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Audi A3 Hatchback.jpg',
        seats: 5,
        luggage: 2,
        horstpower: '200',
        ps: 200,
        consumption: '7.2L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.5,
      },
      {
        vehicleid: 'V055',
        brand: 'Audi',
        model: 'A6 Avant',
        year: 2023,
        vehicletype: 'Wagon',
        colors: 'Black',
        locations: ['München (48.1351,11.5820)'],
        priceperday: 195,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Audi A6 Wagon.png',
        seats: 5,
        luggage: 4,
        horstpower: '252',
        ps: 252,
        consumption: '7.0L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: true,
        rating: 4.6,
      },
      {
        vehicleid: 'V056',
        brand: 'Audi',
        model: 'RS3 Sport',
        year: 2023,
        vehicletype: 'Sedan',
        colors: 'Green',
        locations: ['Frankfurt (50.1100,8.6820)'],
        priceperday: 280,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Audi RS3 Sport.png',
        seats: 5,
        luggage: 2,
        horstpower: '400',
        ps: 400,
        consumption: '9.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: true,
        rating: 4.8,
      },
      {
        vehicleid: 'V057',
        brand: 'Audi',
        model: 'TT',
        year: 2023,
        vehicletype: 'Coupe',
        colors: 'Blue',
        locations: ['Hamburg (53.5511,9.9937)'],
        priceperday: 220,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Audi TT.png',
        seats: 4,
        luggage: 1,
        horstpower: '228',
        ps: 228,
        consumption: '8.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: true,
        rating: 4.7,
      },
      {
        vehicleid: 'V058',
        brand: 'Bentley',
        model: 'Continental GT',
        year: 2023,
        vehicletype: 'Coupe',
        colors: 'Cyan',
        locations: ['Stuttgart (48.7758,9.1829)'],
        priceperday: 650,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Bentley Continental GT.png',
        seats: 4,
        luggage: 2,
        horstpower: '542',
        ps: 542,
        consumption: '13.0L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: true,
        rating: 4.9,
      },
      {
        vehicleid: 'V059',
        brand: 'Cupra',
        model: 'Leon',
        year: 2023,
        vehicletype: 'Hatchback',
        colors: 'Grey',
        locations: ['Düsseldorf (51.2277,6.7735)'],
        priceperday: 140,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Cupra Leon.png',
        seats: 5,
        luggage: 2,
        horstpower: '245',
        ps: 245,
        consumption: '7.2L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.4,
      },
      {
        vehicleid: 'V060',
        brand: 'Dodge',
        model: 'Viper',
        year: 2017,
        vehicletype: 'Coupe',
        colors: 'Red',
        locations: ['Berlin (52.5200,13.4050)'],
        priceperday: 450,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Dodge Viper.png',
        seats: 2,
        luggage: 1,
        horstpower: '645',
        ps: 645,
        consumption: '14.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Manual',
        featured: true,
        rating: 4.9,
      },
      {
        vehicleid: 'V061',
        brand: 'Ferrari',
        model: 'F40',
        year: 1990,
        vehicletype: 'Coupe',
        colors: 'Red',
        locations: ['München (48.1351,11.5820)'],
        priceperday: 750,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Ferrari F40.jpg',
        seats: 2,
        luggage: 1,
        horstpower: '478',
        ps: 478,
        consumption: '10.3L/100km',
        fuel: 'Gasoline',
        geartype: 'Manual',
        featured: true,
        rating: 5.0,
      },
      {
        vehicleid: 'V062',
        brand: 'Ford',
        model: 'Focus',
        year: 2023,
        vehicletype: 'Hatchback',
        colors: 'Dark Blue',
        locations: ['Köln (50.9375,6.9603)'],
        priceperday: 95,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Ford Focus.jpg',
        seats: 5,
        luggage: 2,
        horstpower: '155',
        ps: 155,
        consumption: '6.0L/100km',
        fuel: 'Gasoline',
        geartype: 'Manual',
        featured: false,
        rating: 4.2,
      },
      {
        vehicleid: 'V063',
        brand: 'Honda',
        model: 'Civic',
        year: 2023,
        vehicletype: 'Sedan',
        colors: 'Silver Metallic',
        locations: ['Hannover (52.3759,9.7320)'],
        priceperday: 110,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Honda Civic.png',
        seats: 5,
        luggage: 2,
        horstpower: '180',
        ps: 180,
        consumption: '6.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.5,
      },
      {
        vehicleid: 'V064',
        brand: 'Hyundai',
        model: 'H1',
        year: 2023,
        vehicletype: 'VAN',
        colors: 'White',
        locations: ['Dortmund (51.5136,7.4653)'],
        priceperday: 150,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Hyundai H1.png',
        seats: 9,
        luggage: 4,
        horstpower: '170',
        ps: 170,
        consumption: '8.5L/100km',
        fuel: 'Diesel',
        geartype: 'Automatic',
        featured: false,
        rating: 4.3,
      },
      {
        vehicleid: 'V065',
        brand: 'Jeep',
        model: 'Grand Cherokee',
        year: 2023,
        vehicletype: 'SUV',
        colors: 'Black',
        locations: ['Essen (51.4556,7.0116)'],
        priceperday: 180,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Jeep Grand Cherokee.png',
        seats: 5,
        luggage: 3,
        horstpower: '293',
        ps: 293,
        consumption: '9.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: true,
        rating: 4.6,
      },
      {
        vehicleid: 'V066',
        brand: 'Mazda',
        model: 'CX-30',
        year: 2023,
        vehicletype: 'Crossover',
        colors: 'Grey Metallic',
        locations: ['Wuppertal (51.2562,7.1508)'],
        priceperday: 120,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Mazda CX30.png',
        seats: 5,
        luggage: 2,
        horstpower: '191',
        ps: 191,
        consumption: '7.0L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.4,
      },
      {
        vehicleid: 'V067',
        brand: 'Mercedes-Benz',
        model: 'C 63 AMG',
        year: 2023,
        vehicletype: 'Coupe',
        colors: 'Black',
        locations: ['Dresden (51.0504,13.7373)'],
        priceperday: 350,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Mercedes-Benz C 63 AMG.png',
        seats: 4,
        luggage: 2,
        horstpower: '503',
        ps: 503,
        consumption: '11.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: true,
        rating: 4.9,
      },
      {
        vehicleid: 'V068',
        brand: 'MINI',
        model: 'Clubman',
        year: 2023,
        vehicletype: 'Wagon',
        colors: 'Green Metallic',
        locations: ['Bremen (53.0793,8.8017)'],
        priceperday: 130,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/MINI Clubmann.jpg',
        seats: 5,
        luggage: 3,
        horstpower: '189',
        ps: 189,
        consumption: '6.8L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.3,
      },
      {
        vehicleid: 'V069',
        brand: 'MINI',
        model: 'Cooper D',
        year: 2023,
        vehicletype: 'Hatchback',
        colors: 'Red',
        locations: ['Mannheim (49.489,8.467)'],
        priceperday: 105,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/MINI Cooper D.png',
        seats: 4,
        luggage: 2,
        horstpower: '134',
        ps: 134,
        consumption: '5.5L/100km',
        fuel: 'Diesel',
        geartype: 'Manual',
        featured: false,
        rating: 4.2,
      },
      {
        vehicleid: 'V070',
        brand: 'MINI',
        model: 'Cooper S Countryman',
        year: 2023,
        vehicletype: 'SUV',
        colors: 'Green',
        locations: ['Frankfurt (50.1100,8.6820)'],
        priceperday: 145,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/MINI Cooper S Countryman.png',
        seats: 5,
        luggage: 3,
        horstpower: '228',
        ps: 228,
        consumption: '7.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.5,
      },
      {
        vehicleid: 'V071',
        brand: 'Mitsubishi',
        model: 'Eclipse Cross',
        year: 2023,
        vehicletype: 'SUV',
        colors: 'Blue',
        locations: ['Hamburg (53.5511,9.9937)'],
        priceperday: 125,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Mitsubishi Eclipse Cross.png',
        seats: 5,
        luggage: 2,
        horstpower: '152',
        ps: 152,
        consumption: '7.8L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.1,
      },
      {
        vehicleid: 'V072',
        brand: 'Nissan',
        model: '350Z',
        year: 2008,
        vehicletype: 'Coupe',
        colors: 'Orange',
        locations: ['Stuttgart (48.7758,9.1829)'],
        priceperday: 195,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Nissan Z-350.png',
        seats: 2,
        luggage: 1,
        horstpower: '306',
        ps: 306,
        consumption: '11.0L/100km',
        fuel: 'Gasoline',
        geartype: 'Manual',
        featured: true,
        rating: 4.6,
      },
      {
        vehicleid: 'V073',
        brand: 'Opel',
        model: 'Astra',
        year: 2023,
        vehicletype: 'Hatchback',
        colors: 'Blue',
        locations: ['Düsseldorf (51.2277,6.7735)'],
        priceperday: 100,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Opel Astra.png',
        seats: 5,
        luggage: 2,
        horstpower: '130',
        ps: 130,
        consumption: '5.3L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.2,
      },
      {
        vehicleid: 'V074',
        brand: 'Opel',
        model: 'Corsa',
        year: 2023,
        vehicletype: 'Hatchback',
        colors: 'Yellow',
        locations: ['Köln (50.9375,6.9603)'],
        priceperday: 85,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Opel Corsa.png',
        seats: 5,
        luggage: 2,
        horstpower: '100',
        ps: 100,
        consumption: '4.1L/100km',
        fuel: 'Gasoline',
        geartype: 'Manual',
        featured: false,
        rating: 4.0,
      },
      {
        vehicleid: 'V075',
        brand: 'Opel',
        model: 'Insignia',
        year: 2023,
        vehicletype: 'Sedan',
        colors: 'Grey Metallic',
        locations: ['Berlin (52.5200,13.4050)'],
        priceperday: 135,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Opel Insignia.png',
        seats: 5,
        luggage: 2,
        horstpower: '170',
        ps: 170,
        consumption: '6.5L/100km',
        fuel: 'Diesel',
        geartype: 'Automatic',
        featured: false,
        rating: 4.3,
      },
      {
        vehicleid: 'V076',
        brand: 'Opel',
        model: 'Vivaro',
        year: 2023,
        vehicletype: 'VAN',
        colors: 'White',
        locations: ['München (48.1351,11.5820)'],
        priceperday: 140,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Opel Vivaro.png',
        seats: 9,
        luggage: 4,
        horstpower: '150',
        ps: 150,
        consumption: '7.2L/100km',
        fuel: 'Diesel',
        geartype: 'Automatic',
        featured: false,
        rating: 4.2,
      },
      {
        vehicleid: 'V077',
        brand: 'Opel',
        model: 'Zafira',
        year: 2023,
        vehicletype: 'SUV',
        colors: 'White',
        locations: ['Hannover (52.3759,9.7320)'],
        priceperday: 130,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Opel Zafira.png',
        seats: 7,
        luggage: 3,
        horstpower: '140',
        ps: 140,
        consumption: '6.8L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.1,
      },
      {
        vehicleid: 'V078',
        brand: 'Porsche',
        model: 'Panamera',
        year: 2023,
        vehicletype: 'Sedan',
        colors: 'Black',
        locations: ['Stuttgart (48.7758,9.1829)'],
        priceperday: 420,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Porsche Panamera.png',
        seats: 4,
        luggage: 2,
        horstpower: '325',
        ps: 325,
        consumption: '9.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: true,
        rating: 4.8,
      },
      {
        vehicleid: 'V079',
        brand: 'Range Rover',
        model: 'Range Rover Sport',
        year: 2023,
        vehicletype: 'SUV',
        colors: 'Silver',
        locations: ['Dresden (51.0504,13.7373)'],
        priceperday: 550,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Range Rover.jpg',
        seats: 5,
        luggage: 3,
        horstpower: '395',
        ps: 395,
        consumption: '11.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: true,
        rating: 4.9,
      },
      {
        vehicleid: 'V080',
        brand: 'Renault',
        model: 'Megane',
        year: 2023,
        vehicletype: 'Hatchback',
        colors: 'Red',
        locations: ['Dortmund (51.5136,7.4653)'],
        priceperday: 110,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Renault Megane.jpg',
        seats: 5,
        luggage: 2,
        horstpower: '140',
        ps: 140,
        consumption: '6.2L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.3,
      },
      {
        vehicleid: 'V081',
        brand: 'Skoda',
        model: 'Fabia',
        year: 2023,
        vehicletype: 'Hatchback',
        colors: 'Blue',
        locations: ['Essen (51.4556,7.0116)'],
        priceperday: 90,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Skoda Fabia.png',
        seats: 5,
        luggage: 2,
        horstpower: '115',
        ps: 115,
        consumption: '5.8L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.1,
      },
      {
        vehicleid: 'V082',
        brand: 'Skoda',
        model: 'Kodiaq',
        year: 2023,
        vehicletype: 'SUV',
        colors: 'Blue',
        locations: ['Wuppertal (51.2562,7.1508)'],
        priceperday: 160,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Skoda Kodiaq .png',
        seats: 7,
        luggage: 3,
        horstpower: '190',
        ps: 190,
        consumption: '7.5L/100km',
        fuel: 'Diesel',
        geartype: 'Automatic',
        featured: true,
        rating: 4.5,
      },
      {
        vehicleid: 'V083',
        brand: 'Skoda',
        model: 'Octavia',
        year: 2023,
        vehicletype: 'Sedan',
        colors: 'Blue',
        locations: ['Bremen (53.0793,8.8017)'],
        priceperday: 115,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Skoda Octavia.png',
        seats: 5,
        luggage: 2,
        horstpower: '150',
        ps: 150,
        consumption: '5.7L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.4,
      },
      {
        vehicleid: 'V084',
        brand: 'Tesla',
        model: 'Model S',
        year: 2023,
        vehicletype: 'Sedan',
        colors: 'Black',
        locations: ['Mannheim (49.489,8.467)'],
        priceperday: 380,
        availability: true,
        electricvehicle: true,
        carimg: '/cars/Tesla Model S.jpg',
        seats: 5,
        luggage: 2,
        horstpower: '670',
        ps: 670,
        consumption: '0L/100km',
        fuel: 'Electric',
        geartype: 'Automatic',
        featured: true,
        rating: 4.9,
      },
      {
        vehicleid: 'V085',
        brand: 'Toyota',
        model: 'Aygo',
        year: 2023,
        vehicletype: 'Hatchback',
        colors: 'Black',
        locations: ['Frankfurt (50.1100,8.6820)'],
        priceperday: 70,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Toyota Ayris.png',
        seats: 4,
        luggage: 1,
        horstpower: '72',
        ps: 72,
        consumption: '4.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Manual',
        featured: false,
        rating: 3.9,
      },
      {
        vehicleid: 'V086',
        brand: 'Toyota',
        model: 'Camry',
        year: 2023,
        vehicletype: 'Sedan',
        colors: 'Blue',
        locations: ['Hamburg (53.5511,9.9937)'],
        priceperday: 140,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Toyota Camry.jpg',
        seats: 5,
        luggage: 2,
        horstpower: '203',
        ps: 203,
        consumption: '7.0L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.5,
      },
      {
        vehicleid: 'V087',
        brand: 'Toyota',
        model: 'Corolla',
        year: 2023,
        vehicletype: 'Sedan',
        colors: 'Black',
        locations: ['Stuttgart (48.7758,9.1829)'],
        priceperday: 105,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Toyota Corolla.jpg',
        seats: 5,
        luggage: 2,
        horstpower: '169',
        ps: 169,
        consumption: '6.2L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.4,
      },
      {
        vehicleid: 'V088',
        brand: 'Toyota',
        model: 'Corolla Touring Sports',
        year: 2023,
        vehicletype: 'Wagon',
        colors: 'White',
        locations: ['Düsseldorf (51.2277,6.7735)'],
        priceperday: 115,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Toyota Corolla Wagon.jpg',
        seats: 5,
        luggage: 4,
        horstpower: '169',
        ps: 169,
        consumption: '6.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.4,
      },
      {
        vehicleid: 'V089',
        brand: 'Toyota',
        model: 'Hiace',
        year: 2023,
        vehicletype: 'VAN',
        colors: 'White',
        locations: ['Köln (50.9375,6.9603)'],
        priceperday: 155,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Toyota Hiace.png',
        seats: 12,
        luggage: 4,
        horstpower: '174',
        ps: 174,
        consumption: '9.0L/100km',
        fuel: 'Diesel',
        geartype: 'Manual',
        featured: false,
        rating: 4.2,
      },
      {
        vehicleid: 'V090',
        brand: 'Volkswagen',
        model: 'Polo',
        year: 2023,
        vehicletype: 'Hatchback',
        colors: 'Black Metallic',
        locations: ['Berlin (52.5200,13.4050)'],
        priceperday: 95,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Volkswagen Polo.png',
        seats: 5,
        luggage: 2,
        horstpower: '113',
        ps: 113,
        consumption: '5.5L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.2,
      },
      {
        vehicleid: 'V091',
        brand: 'Volkswagen',
        model: 'Touran',
        year: 2023,
        vehicletype: 'SUV',
        colors: 'Blue',
        locations: ['München (48.1351,11.5820)'],
        priceperday: 135,
        availability: true,
        electricvehicle: false,
        carimg: '/cars/Volkswagen Touran.png',
        seats: 7,
        luggage: 3,
        horstpower: '150',
        ps: 150,
        consumption: '6.8L/100km',
        fuel: 'Gasoline',
        geartype: 'Automatic',
        featured: false,
        rating: 4.3,
      },
    ];

    for (const vehicle of vehicles) {
      // Определяем количество дверей на основе типа автомобиля
      let doors = 4; // По умолчанию 4 двери
      if (vehicle.vehicletype === 'Coupe') {
        doors = 2;
      } else if (vehicle.vehicletype === 'Van' || vehicle.vehicletype === 'SUV') {
        doors = 5;
      } else if (vehicle.vehicletype === 'Sedan' || vehicle.vehicletype === 'Wagon' || vehicle.vehicletype === 'Hatchback') {
        doors = 4;
      } else if (vehicle.vehicletype === 'Crossover') {
        doors = 5;
      }

      await pool.query(
        `INSERT INTO vehicles (
          vehicleid, brand, model, year, vehicletype, colors, locations,
          priceperday, availability, electricvehicle, carimg, seats, doors, luggage,
          horstpower, ps, consumption, fuel, geartype, featured, rating
        ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21)
        ON CONFLICT (vehicleid) DO UPDATE SET
          brand = EXCLUDED.brand,
          model = EXCLUDED.model,
          year = EXCLUDED.year,
          vehicletype = EXCLUDED.vehicletype,
          colors = EXCLUDED.colors,
          locations = EXCLUDED.locations,
          priceperday = EXCLUDED.priceperday,
          availability = EXCLUDED.availability,
          electricvehicle = EXCLUDED.electricvehicle,
          carimg = EXCLUDED.carimg,
          seats = EXCLUDED.seats,
          doors = EXCLUDED.doors,
          luggage = EXCLUDED.luggage,
          horstpower = EXCLUDED.horstpower,
          ps = EXCLUDED.ps,
          consumption = EXCLUDED.consumption,
          fuel = EXCLUDED.fuel,
          geartype = EXCLUDED.geartype,
          featured = EXCLUDED.featured,
          rating = EXCLUDED.rating`,
        [
          vehicle.vehicleid,
          vehicle.brand,
          vehicle.model,
          vehicle.year,
          vehicle.vehicletype,
          vehicle.colors,
          vehicle.locations,
          vehicle.priceperday,
          vehicle.availability,
          vehicle.electricvehicle,
          vehicle.carimg,
          vehicle.seats,
          doors,
          vehicle.luggage,
          vehicle.horstpower,
          vehicle.ps,
          vehicle.consumption,
          vehicle.fuel,
          vehicle.geartype,
          vehicle.featured,
          vehicle.rating,
        ]
      );

      // Create sample reviews
      const reviews = [
        {
          vehicleid: vehicle.vehicleid,
          name: 'John Doe',
          text: 'Great car, very comfortable and reliable!',
          stars: 5,
          date: '2024-01-15',
        },
        {
          vehicleid: vehicle.vehicleid,
          name: 'Jane Smith',
          text: 'Excellent service and the car was in perfect condition.',
          stars: 4,
          date: '2024-01-20',
        },
      ];

      for (const review of reviews) {
        await pool.query(
          `INSERT INTO reviews (id, vehicleid, name, text, stars, date)
           VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT DO NOTHING`,
          [uuidv4(), review.vehicleid, review.name, review.text, review.stars, review.date]
        );
      }
    }

    console.log('✅ Database seeded successfully!');
    console.log('📧 Test user: test@example.com');
    console.log('🔑 Test password: password123');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding failed:', error);
    process.exit(1);
  }
}

seed();

