// Country codes with phone codes and names
export const countryCodes = [
  { code: "AD", phone: "+376", name: "Andorra" },
  { code: "AE", phone: "+971", name: "United Arab Emirates" },
  { code: "AF", phone: "+93", name: "Afghanistan" },
  { code: "AG", phone: "+1", name: "Antigua and Barbuda" },
  { code: "AI", phone: "+1", name: "Anguilla" },
  { code: "AL", phone: "+355", name: "Albania" },
  { code: "AM", phone: "+374", name: "Armenia" },
  { code: "AO", phone: "+244", name: "Angola" },
  { code: "AQ", phone: "+672", name: "Antarctica" },
  { code: "AR", phone: "+54", name: "Argentina" },
  { code: "AS", phone: "+1", name: "American Samoa" },
  { code: "AT", phone: "+43", name: "Austria" },
  { code: "AU", phone: "+61", name: "Australia" },
  { code: "AW", phone: "+297", name: "Aruba" },
  { code: "AX", phone: "+358", name: "Åland Islands" },
  { code: "AZ", phone: "+994", name: "Azerbaijan" },
  { code: "BA", phone: "+387", name: "Bosnia and Herzegovina" },
  { code: "BB", phone: "+1", name: "Barbados" },
  { code: "BD", phone: "+880", name: "Bangladesh" },
  { code: "BE", phone: "+32", name: "Belgium" },
  { code: "BF", phone: "+226", name: "Burkina Faso" },
  { code: "BG", phone: "+359", name: "Bulgaria" },
  { code: "BH", phone: "+973", name: "Bahrain" },
  { code: "BI", phone: "+257", name: "Burundi" },
  { code: "BJ", phone: "+229", name: "Benin" },
  { code: "BL", phone: "+590", name: "Saint Barthélemy" },
  { code: "BM", phone: "+1", name: "Bermuda" },
  { code: "BN", phone: "+673", name: "Brunei" },
  { code: "BO", phone: "+591", name: "Bolivia" },
  { code: "BQ", phone: "+599", name: "Caribbean Netherlands" },
  { code: "BR", phone: "+55", name: "Brazil" },
  { code: "BS", phone: "+1", name: "Bahamas" },
  { code: "BT", phone: "+975", name: "Bhutan" },
  { code: "BV", phone: "+47", name: "Bouvet Island" },
  { code: "BW", phone: "+267", name: "Botswana" },
  { code: "BY", phone: "+375", name: "Belarus" },
  { code: "BZ", phone: "+501", name: "Belize" },
  { code: "CA", phone: "+1", name: "Canada" },
  { code: "CC", phone: "+61", name: "Cocos Islands" },
  { code: "CD", phone: "+243", name: "DR Congo" },
  { code: "CF", phone: "+236", name: "Central African Republic" },
  { code: "CG", phone: "+242", name: "Republic of the Congo" },
  { code: "CH", phone: "+41", name: "Switzerland" },
  { code: "CI", phone: "+225", name: "Côte d'Ivoire" },
  { code: "CK", phone: "+682", name: "Cook Islands" },
  { code: "CL", phone: "+56", name: "Chile" },
  { code: "CM", phone: "+237", name: "Cameroon" },
  { code: "CN", phone: "+86", name: "China" },
  { code: "CO", phone: "+57", name: "Colombia" },
  { code: "CR", phone: "+506", name: "Costa Rica" },
  { code: "CU", phone: "+53", name: "Cuba" },
  { code: "CV", phone: "+238", name: "Cape Verde" },
  { code: "CW", phone: "+599", name: "Curaçao" },
  { code: "CX", phone: "+61", name: "Christmas Island" },
  { code: "CY", phone: "+357", name: "Cyprus" },
  { code: "CZ", phone: "+420", name: "Czech Republic" },
  { code: "DE", phone: "+49", name: "Germany" },
  { code: "DJ", phone: "+253", name: "Djibouti" },
  { code: "DK", phone: "+45", name: "Denmark" },
  { code: "DM", phone: "+1", name: "Dominica" },
  { code: "DO", phone: "+1", name: "Dominican Republic" },
  { code: "DZ", phone: "+213", name: "Algeria" },
  { code: "EC", phone: "+593", name: "Ecuador" },
  { code: "EE", phone: "+372", name: "Estonia" },
  { code: "EG", phone: "+20", name: "Egypt" },
  { code: "EH", phone: "+212", name: "Western Sahara" },
  { code: "ER", phone: "+291", name: "Eritrea" },
  { code: "ES", phone: "+34", name: "Spain" },
  { code: "ET", phone: "+251", name: "Ethiopia" },
  { code: "FI", phone: "+358", name: "Finland" },
  { code: "FJ", phone: "+679", name: "Fiji" },
  { code: "FK", phone: "+500", name: "Falkland Islands" },
  { code: "FM", phone: "+691", name: "Micronesia" },
  { code: "FO", phone: "+298", name: "Faroe Islands" },
  { code: "FR", phone: "+33", name: "France" },
  { code: "GA", phone: "+241", name: "Gabon" },
  { code: "GB", phone: "+44", name: "United Kingdom" },
  { code: "GD", phone: "+1", name: "Grenada" },
  { code: "GE", phone: "+995", name: "Georgia" },
  { code: "GF", phone: "+594", name: "French Guiana" },
  { code: "GG", phone: "+44", name: "Guernsey" },
  { code: "GH", phone: "+233", name: "Ghana" },
  { code: "GI", phone: "+350", name: "Gibraltar" },
  { code: "GL", phone: "+299", name: "Greenland" },
  { code: "GM", phone: "+220", name: "Gambia" },
  { code: "GN", phone: "+224", name: "Guinea" },
  { code: "GP", phone: "+590", name: "Guadeloupe" },
  { code: "GQ", phone: "+240", name: "Equatorial Guinea" },
  { code: "GR", phone: "+30", name: "Greece" },
  { code: "GS", phone: "+500", name: "South Georgia" },
  { code: "GT", phone: "+502", name: "Guatemala" },
  { code: "GU", phone: "+1", name: "Guam" },
  { code: "GW", phone: "+245", name: "Guinea-Bissau" },
  { code: "GY", phone: "+592", name: "Guyana" },
  { code: "HK", phone: "+852", name: "Hong Kong" },
  { code: "HM", phone: "+672", name: "Heard Island" },
  { code: "HN", phone: "+504", name: "Honduras" },
  { code: "HR", phone: "+385", name: "Croatia" },
  { code: "HT", phone: "+509", name: "Haiti" },
  { code: "HU", phone: "+36", name: "Hungary" },
  { code: "ID", phone: "+62", name: "Indonesia" },
  { code: "IE", phone: "+353", name: "Ireland" },
  { code: "IL", phone: "+972", name: "Israel" },
  { code: "IM", phone: "+44", name: "Isle of Man" },
  { code: "IN", phone: "+91", name: "India" },
  { code: "IO", phone: "+246", name: "British Indian Ocean Territory" },
  { code: "IQ", phone: "+964", name: "Iraq" },
  { code: "IR", phone: "+98", name: "Iran" },
  { code: "IS", phone: "+354", name: "Iceland" },
  { code: "IT", phone: "+39", name: "Italy" },
  { code: "JE", phone: "+44", name: "Jersey" },
  { code: "JM", phone: "+1", name: "Jamaica" },
  { code: "JO", phone: "+962", name: "Jordan" },
  { code: "JP", phone: "+81", name: "Japan" },
  { code: "KE", phone: "+254", name: "Kenya" },
  { code: "KG", phone: "+996", name: "Kyrgyzstan" },
  { code: "KH", phone: "+855", name: "Cambodia" },
  { code: "KI", phone: "+686", name: "Kiribati" },
  { code: "KM", phone: "+269", name: "Comoros" },
  { code: "KN", phone: "+1", name: "Saint Kitts and Nevis" },
  { code: "KP", phone: "+850", name: "North Korea" },
  { code: "KR", phone: "+82", name: "South Korea" },
  { code: "KW", phone: "+965", name: "Kuwait" },
  { code: "KY", phone: "+1", name: "Cayman Islands" },
  { code: "KZ", phone: "+7", name: "Kazakhstan" },
  { code: "LA", phone: "+856", name: "Laos" },
  { code: "LB", phone: "+961", name: "Lebanon" },
  { code: "LC", phone: "+1", name: "Saint Lucia" },
  { code: "LI", phone: "+423", name: "Liechtenstein" },
  { code: "LK", phone: "+94", name: "Sri Lanka" },
  { code: "LR", phone: "+231", name: "Liberia" },
  { code: "LS", phone: "+266", name: "Lesotho" },
  { code: "LT", phone: "+370", name: "Lithuania" },
  { code: "LU", phone: "+352", name: "Luxembourg" },
  { code: "LV", phone: "+371", name: "Latvia" },
  { code: "LY", phone: "+218", name: "Libya" },
  { code: "MA", phone: "+212", name: "Morocco" },
  { code: "MC", phone: "+377", name: "Monaco" },
  { code: "MD", phone: "+373", name: "Moldova" },
  { code: "ME", phone: "+382", name: "Montenegro" },
  { code: "MF", phone: "+590", name: "Saint Martin" },
  { code: "MG", phone: "+261", name: "Madagascar" },
  { code: "MH", phone: "+692", name: "Marshall Islands" },
  { code: "MK", phone: "+389", name: "North Macedonia" },
  { code: "ML", phone: "+223", name: "Mali" },
  { code: "MM", phone: "+95", name: "Myanmar" },
  { code: "MN", phone: "+976", name: "Mongolia" },
  { code: "MO", phone: "+853", name: "Macau" },
  { code: "MP", phone: "+1", name: "Northern Mariana Islands" },
  { code: "MQ", phone: "+596", name: "Martinique" },
  { code: "MR", phone: "+222", name: "Mauritania" },
  { code: "MS", phone: "+1", name: "Montserrat" },
  { code: "MT", phone: "+356", name: "Malta" },
  { code: "MU", phone: "+230", name: "Mauritius" },
  { code: "MV", phone: "+960", name: "Maldives" },
  { code: "MW", phone: "+265", name: "Malawi" },
  { code: "MX", phone: "+52", name: "Mexico" },
  { code: "MY", phone: "+60", name: "Malaysia" },
  { code: "MZ", phone: "+258", name: "Mozambique" },
  { code: "NA", phone: "+264", name: "Namibia" },
  { code: "NC", phone: "+687", name: "New Caledonia" },
  { code: "NE", phone: "+227", name: "Niger" },
  { code: "NF", phone: "+672", name: "Norfolk Island" },
  { code: "NG", phone: "+234", name: "Nigeria" },
  { code: "NI", phone: "+505", name: "Nicaragua" },
  { code: "NL", phone: "+31", name: "Netherlands" },
  { code: "NO", phone: "+47", name: "Norway" },
  { code: "NP", phone: "+977", name: "Nepal" },
  { code: "NR", phone: "+674", name: "Nauru" },
  { code: "NU", phone: "+683", name: "Niue" },
  { code: "NZ", phone: "+64", name: "New Zealand" },
  { code: "OM", phone: "+968", name: "Oman" },
  { code: "PA", phone: "+507", name: "Panama" },
  { code: "PE", phone: "+51", name: "Peru" },
  { code: "PF", phone: "+689", name: "French Polynesia" },
  { code: "PG", phone: "+675", name: "Papua New Guinea" },
  { code: "PH", phone: "+63", name: "Philippines" },
  { code: "PK", phone: "+92", name: "Pakistan" },
  { code: "PL", phone: "+48", name: "Poland" },
  { code: "PM", phone: "+508", name: "Saint Pierre and Miquelon" },
  { code: "PN", phone: "+872", name: "Pitcairn" },
  { code: "PR", phone: "+1", name: "Puerto Rico" },
  { code: "PS", phone: "+970", name: "Palestine" },
  { code: "PT", phone: "+351", name: "Portugal" },
  { code: "PW", phone: "+680", name: "Palau" },
  { code: "PY", phone: "+595", name: "Paraguay" },
  { code: "QA", phone: "+974", name: "Qatar" },
  { code: "RE", phone: "+262", name: "Réunion" },
  { code: "RO", phone: "+40", name: "Romania" },
  { code: "RS", phone: "+381", name: "Serbia" },
  { code: "RU", phone: "+7", name: "Russia" },
  { code: "RW", phone: "+250", name: "Rwanda" },
  { code: "SA", phone: "+966", name: "Saudi Arabia" },
  { code: "SB", phone: "+677", name: "Solomon Islands" },
  { code: "SC", phone: "+248", name: "Seychelles" },
  { code: "SD", phone: "+249", name: "Sudan" },
  { code: "SE", phone: "+46", name: "Sweden" },
  { code: "SG", phone: "+65", name: "Singapore" },
  { code: "SH", phone: "+290", name: "Saint Helena" },
  { code: "SI", phone: "+386", name: "Slovenia" },
  { code: "SJ", phone: "+47", name: "Svalbard and Jan Mayen" },
  { code: "SK", phone: "+421", name: "Slovakia" },
  { code: "SL", phone: "+232", name: "Sierra Leone" },
  { code: "SM", phone: "+378", name: "San Marino" },
  { code: "SN", phone: "+221", name: "Senegal" },
  { code: "SO", phone: "+252", name: "Somalia" },
  { code: "SR", phone: "+597", name: "Suriname" },
  { code: "SS", phone: "+211", name: "South Sudan" },
  { code: "ST", phone: "+239", name: "São Tomé and Príncipe" },
  { code: "SV", phone: "+503", name: "El Salvador" },
  { code: "SX", phone: "+1", name: "Sint Maarten" },
  { code: "SY", phone: "+963", name: "Syria" },
  { code: "SZ", phone: "+268", name: "Eswatini" },
  { code: "TC", phone: "+1", name: "Turks and Caicos Islands" },
  { code: "TD", phone: "+235", name: "Chad" },
  { code: "TF", phone: "+262", name: "French Southern Territories" },
  { code: "TG", phone: "+228", name: "Togo" },
  { code: "TH", phone: "+66", name: "Thailand" },
  { code: "TJ", phone: "+992", name: "Tajikistan" },
  { code: "TK", phone: "+690", name: "Tokelau" },
  { code: "TL", phone: "+670", name: "Timor-Leste" },
  { code: "TM", phone: "+993", name: "Turkmenistan" },
  { code: "TN", phone: "+216", name: "Tunisia" },
  { code: "TO", phone: "+676", name: "Tonga" },
  { code: "TR", phone: "+90", name: "Turkey" },
  { code: "TT", phone: "+1", name: "Trinidad and Tobago" },
  { code: "TV", phone: "+688", name: "Tuvalu" },
  { code: "TW", phone: "+886", name: "Taiwan" },
  { code: "TZ", phone: "+255", name: "Tanzania" },
  { code: "UA", phone: "+380", name: "Ukraine" },
  { code: "UG", phone: "+256", name: "Uganda" },
  { code: "UM", phone: "+1", name: "United States Minor Outlying Islands" },
  { code: "US", phone: "+1", name: "United States" },
  { code: "UY", phone: "+598", name: "Uruguay" },
  { code: "UZ", phone: "+998", name: "Uzbekistan" },
  { code: "VA", phone: "+39", name: "Vatican City" },
  { code: "VC", phone: "+1", name: "Saint Vincent and the Grenadines" },
  { code: "VE", phone: "+58", name: "Venezuela" },
  { code: "VG", phone: "+1", name: "British Virgin Islands" },
  { code: "VI", phone: "+1", name: "United States Virgin Islands" },
  { code: "VN", phone: "+84", name: "Vietnam" },
  { code: "VU", phone: "+678", name: "Vanuatu" },
  { code: "WF", phone: "+681", name: "Wallis and Futuna" },
  { code: "WS", phone: "+685", name: "Samoa" },
  { code: "XK", phone: "+383", name: "Kosovo" },
  { code: "YE", phone: "+967", name: "Yemen" },
  { code: "YT", phone: "+262", name: "Mayotte" },
  { code: "ZA", phone: "+27", name: "South Africa" },
  { code: "ZM", phone: "+260", name: "Zambia" },
  { code: "ZW", phone: "+263", name: "Zimbabwe" },
];

// Countries list for address
export const countries = countryCodes.map((c) => ({
  code: c.code,
  name: c.name,
}));
